---
- name: Run Orcha Local Tasks
  hosts: 127.0.0.1
  connection: local
  vars:
    serverName: orcha
tasks:
  - name: Install NodeJS
    apt: name=nodejs=0.10.37~dfsg2-2ubuntu1 state=present
  - name: Install NPM
    apt: name=npm state=present
  - name: Create symlink to node
    file: src='/usr/bin/nodejs' dest='/usr/bin/node' owner='orcha' group='orcha' state='link'
  - name: Create Directory for Code
    file: path=/home/orcha/proj/aurora state=directory owner=orcha group=orcha
  - name: check out code from github
    git: repo=git@github.com/MythSoftware/aurora.git dest=/home/orcha/proj/aurora accept_hostkey=yes
    register: latest_code
  - set_fact: git_version={{ latest_code.after }}
  - set_fact: git_changed={{ latest_code.changed }}
